remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: "ChimpChat"
description: "AI meets simian wit. AI communication reimagined for the evolved primate ğŸ¤–ğŸµ"

#show_downloads: "false"
